showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    25

    requiredRam:        2.0

    internetCheckUrl:
        - https://google.com
        - https://kiroproject.be

    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen

    required:
        - ram
        - storage
        - root

geoip:
    style:    "json"
    url:      "https://geoip.kde.org/v1/calamares"
    selector: ""
