#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Calamares module that installs the live ISO's kernel into the target,
independent of which kernel package the ISO shipped (linux, linux-lqx,
linux-zen, ...).

It detects the kernel from the live boot medium, copies the image into the
target /boot, generates a matching mkinitcpio preset, and removes the
live-only preset artifacts so the later `mkinitcpio -P` builds exactly one
correct initramfs. This replaces the old hardcoded unpackfs@vmlinuz copy and
the linux-lqx preset rename in kiro_before.
"""

import glob
import os
import shutil
import libcalamares

# Where archiso exposes the booted kernel image on the live medium.
BOOTMNT_KERNEL_GLOB = "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-*"

# Live-only mkinitcpio presets shipped in the airootfs that must not survive
# into the installed system: 'kiro' is the old static preset, 'linux.preset'
# is the archiso live preset.
LIVE_PRESET_ARTIFACTS = ("kiro", "linux.preset")


def detect_kernel():
    """Return (image_path, kernel_name) from the live medium, or (None, None)."""
    matches = sorted(glob.glob(BOOTMNT_KERNEL_GLOB))
    if not matches:
        return None, None
    src = matches[0]
    if len(matches) > 1:
        libcalamares.utils.warning(f"Multiple kernel images found, using first: {matches}")
    kernel = os.path.basename(src)[len("vmlinuz-"):]
    return src, kernel


def copy_kernel_image(src, kernel, target_root):
    """Copy vmlinuz-<kernel> from the live medium into the target /boot."""
    boot_dir = os.path.join(target_root, "boot")
    os.makedirs(boot_dir, exist_ok=True)
    dst = os.path.join(boot_dir, f"vmlinuz-{kernel}")
    libcalamares.utils.debug(f"Copying kernel image {src} -> {dst}")
    shutil.copy2(src, dst)


def write_preset(kernel, target_root):
    """Generate /etc/mkinitcpio.d/<kernel>.preset with a single default image."""
    preset_dir = os.path.join(target_root, "etc/mkinitcpio.d")
    os.makedirs(preset_dir, exist_ok=True)
    preset_path = os.path.join(preset_dir, f"{kernel}.preset")
    content = (
        "# mkinitcpio preset file - generated by Calamares (kiro_kernel)\n"
        f"ALL_kver='/boot/vmlinuz-{kernel}'\n"
        "PRESETS=('default')\n"
        f'default_image="/boot/initramfs-{kernel}.img"\n'
    )
    libcalamares.utils.debug(f"Writing mkinitcpio preset {preset_path}")
    with open(preset_path, "w") as f:
        f.write(content)


def remove_live_presets(target_root):
    """Remove live-only mkinitcpio preset artifacts from the target."""
    preset_dir = os.path.join(target_root, "etc/mkinitcpio.d")
    for name in LIVE_PRESET_ARTIFACTS:
        path = os.path.join(preset_dir, name)
        if os.path.exists(path):
            libcalamares.utils.debug(f"Removing live-only preset artifact: {path}")
            os.remove(path)


def run():
    """Install the live kernel into the target, kernel-agnostically."""
    libcalamares.utils.debug("##############################################")
    libcalamares.utils.debug("Start kiro_kernel")
    libcalamares.utils.debug("##############################################\n")

    target_root = libcalamares.globalstorage.value("rootMountPoint")

    src, kernel = detect_kernel()
    if kernel is None:
        msg = f"No kernel image found at {BOOTMNT_KERNEL_GLOB}"
        libcalamares.utils.warning(msg)
        return ("kiro_kernel: no kernel found", msg)

    libcalamares.utils.debug(f"Detected kernel: {kernel}")

    try:
        copy_kernel_image(src, kernel, target_root)
        write_preset(kernel, target_root)
        remove_live_presets(target_root)
    except Exception as e:
        libcalamares.utils.warning(str(e))
        return ("kiro_kernel: error", f"Failed to install kernel '{kernel}': <pre>{e}</pre>")

    # Expose the detected kernel name for downstream modules / debugging.
    libcalamares.globalstorage.insert("kiroKernel", kernel)

    libcalamares.utils.debug("##############################################")
    libcalamares.utils.debug(f"End kiro_kernel - installed kernel '{kernel}'")
    libcalamares.utils.debug("##############################################\n")
    return None
