#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Calamares module that installs the live ISO's kernel into the target,
independent of which kernel package the ISO shipped (linux, linux-cachyos,
linux-zen, ...).

It detects the kernel from the live boot medium, copies the image into the
target /boot, generates a matching mkinitcpio preset, and removes the
live-only preset artifacts so the later `mkinitcpio -P` builds exactly one
correct initramfs. This replaces the old hardcoded unpackfs@vmlinuz copy and
the hardcoded preset rename in kiro_before.
"""

import glob
import os
import shutil
import libcalamares

# Where archiso exposes the booted kernel image on the live medium.
BOOTMNT_KERNEL_GLOB = "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-*"

# Live-only mkinitcpio presets shipped in the airootfs that must not survive
# into the installed system: 'kiro' is the old static preset, 'linux.preset'
# is the archiso live preset.
LIVE_PRESET_ARTIFACTS = ("kiro", "linux.preset")

# Arch records the package a kernel's module tree belongs to in this file.
# It is the only reliable version -> package mapping: the plain 'linux'
# package builds '<ver>-arch1-N', which carries no package name of its own.
PKGBASE_PATH = "/usr/lib/modules/{release}/pkgbase"

# Where the primary kernel is recorded for the target, so that
# 95-kiro-sort-key.install can keep sorting its boot entry first on every
# later kernel-install run.
PRIMARY_KERNEL_PATH = "etc/kiro/primary-kernel"


def detect_kernels():
    """Return [(image_path, kernel_name), ...] for every kernel on the live medium."""
    return [
        (src, os.path.basename(src)[len("vmlinuz-"):])
        for src in sorted(glob.glob(BOOTMNT_KERNEL_GLOB))
    ]


def copy_kernel_image(src, kernel, target_root):
    """Copy vmlinuz-<kernel> from the live medium into the target /boot."""
    boot_dir = os.path.join(target_root, "boot")
    os.makedirs(boot_dir, exist_ok=True)
    dst = os.path.join(boot_dir, f"vmlinuz-{kernel}")
    libcalamares.utils.debug(f"Copying kernel image {src} -> {dst}")
    shutil.copy2(src, dst)


def write_preset(kernel, target_root):
    """Generate /etc/mkinitcpio.d/<kernel>.preset with a single default image."""
    preset_dir = os.path.join(target_root, "etc/mkinitcpio.d")
    os.makedirs(preset_dir, exist_ok=True)
    preset_path = os.path.join(preset_dir, f"{kernel}.preset")
    content = (
        "# mkinitcpio preset file - generated by Calamares (kiro_kernel)\n"
        f"ALL_kver='/boot/vmlinuz-{kernel}'\n"
        "PRESETS=('default')\n"
        f'default_image="/boot/initramfs-{kernel}.img"\n'
    )
    libcalamares.utils.debug(f"Writing mkinitcpio preset {preset_path}")
    with open(preset_path, "w") as f:
        f.write(content)


def booted_kernel_package():
    """Return the package name of the kernel this live session booted, or None."""
    try:
        with open(PKGBASE_PATH.format(release=os.uname().release)) as f:
            return f.read().strip()
    except OSError:
        return None


def write_primary_kernel(package, target_root):
    """Record the primary kernel package in the target."""
    path = os.path.join(target_root, PRIMARY_KERNEL_PATH)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    libcalamares.utils.debug(f"Recording primary kernel {package} in {path}")
    with open(path, "w") as f:
        f.write(package + "\n")


def remove_live_presets(target_root):
    """Remove live-only mkinitcpio preset artifacts from the target."""
    preset_dir = os.path.join(target_root, "etc/mkinitcpio.d")
    for name in LIVE_PRESET_ARTIFACTS:
        path = os.path.join(preset_dir, name)
        if os.path.exists(path):
            libcalamares.utils.debug(f"Removing live-only preset artifact: {path}")
            os.remove(path)


def run():
    """Install the live kernel into the target, kernel-agnostically."""
    libcalamares.utils.debug("##############################################")
    libcalamares.utils.debug("Start kiro_kernel")
    libcalamares.utils.debug("##############################################\n")

    target_root = libcalamares.globalstorage.value("rootMountPoint")

    kernels = detect_kernels()
    if not kernels:
        msg = f"No kernel image found at {BOOTMNT_KERNEL_GLOB}"
        libcalamares.utils.warning(msg)
        return ("kiro_kernel: no kernel found", msg)

    names = [name for _, name in kernels]
    libcalamares.utils.debug(f"Detected kernel(s): {', '.join(names)}")

    try:
        # Remove the live-only presets FIRST: when the plain 'linux' kernel is one of
        # the installed kernels, write_preset() below regenerates a real linux.preset
        # that must not then be deleted as an archiso artifact.
        remove_live_presets(target_root)
        for src, name in kernels:
            copy_kernel_image(src, name, target_root)
            write_preset(name, target_root)
    except Exception as e:
        libcalamares.utils.warning(str(e))
        return ("kiro_kernel: error", f"Failed to install kernel(s) {names}: <pre>{e}</pre>")

    # The primary kernel is the one the user actually booted, not the
    # alphabetically first: someone who picked the fallback entry because the
    # primary will not boot on their hardware must not be installed a system
    # that defaults back to it.
    primary = booted_kernel_package()
    if primary not in names:
        libcalamares.utils.warning(
            f"Booted kernel package {primary!r} is not among {names} - falling back to {names[0]}")
        primary = names[0]
    write_primary_kernel(primary, target_root)

    # Expose for downstream modules: the primary, plus the full list.
    libcalamares.globalstorage.insert("kiroKernel", primary)
    libcalamares.globalstorage.insert("kiroKernels", names)

    libcalamares.utils.debug("##############################################")
    libcalamares.utils.debug(f"End kiro_kernel - installed kernel(s): {', '.join(names)}")
    libcalamares.utils.debug("##############################################\n")
    return None
